### ISSUE TITLE
Failed to retrieve favicons

### ISSUE THREAD

**Issue by Offerel** [SSilence/selfoss#1109]
Using version 2.18 now (only a testinstall). After first install and importing a OPML file, i changed Sources from "RSS Feed" (which seems to be the default) to "RSS Feed (with FullTextRSS)". After that change, i get the full RSS content, but the Favicon is broken. In errorlog i see the following entry (example):

```
[2019-06-19 20:55:39] selfoss.ERROR: failed to retrieve image https://kolabian.wordpress.com/favicon.ico, {"exception":"[object] (GuzzleHttp\\Exception\\RequestException(code: 0): cURL error 51: SSL: no alternative certificate subject name matches target host name 's1.wp.com' at /var/www/html/selfoss/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:51, GuzzleHttp\\Ring\\Exception\\RingException(code: 0): cURL error 51: SSL: no alternative certificate subject name matches target host name 's1.wp.com' at /var/www/html/selfoss/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:127)
[stacktrace]
#0 /var/www/html/selfoss/vendor/guzzlehttp/guzzle/src/RequestFsm.php(103): GuzzleHttp\\Exception\\RequestException::wrapException(Object(GuzzleHttp\\Message\\Request), Object(GuzzleHttp\\Ring\\Exception\\RingException))
#1 /var/www/html/selfoss/vendor/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\\RequestFsm->__invoke(Object(GuzzleHttp\\Transaction))
#2 /var/www/html/selfoss/vendor/react/promise/src/FulfilledPromise.php(25): GuzzleHttp\\RequestFsm->GuzzleHttp\\{closure}(Array)
#3 /var/www/html/selfoss/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL, NULL)
#4 /var/www/html/selfoss/vendor/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\\Ring\\Future\\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#5 /var/www/html/selfoss/vendor/guzzlehttp/guzzle/src/RequestFsm.php(134): GuzzleHttp\\Message\\FutureResponse::proxy(Object(GuzzleHttp\\Ring\\Future\\CompletedFutureArray), Object(Closure))
#6 /var/www/html/selfoss/vendor/guzzlehttp/guzzle/src/RequestFsm.php(132): GuzzleHttp\\RequestFsm->__invoke(Object(GuzzleHttp\\Transaction))
#7 /var/www/html/selfoss/vendor/react/promise/src/FulfilledPromise.php(25): GuzzleHttp\\RequestFsm->GuzzleHttp\\{closure}(Array)
#8 /var/www/html/selfoss/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php(55): React\\Promise\\FulfilledPromise->then(Object(Closure), NULL, NULL)
#9 /var/www/html/selfoss/vendor/guzzlehttp/guzzle/src/Message/FutureResponse.php(43): GuzzleHttp\\Ring\\Future\\CompletedFutureValue->then(Object(Closure), NULL, NULL)
#10 /var/www/html/selfoss/vendor/guzzlehttp/guzzle/src/RequestFsm.php(134): GuzzleHttp\\Message\\FutureResponse::proxy(Object(GuzzleHttp\\Ring\\Future\\CompletedFutureArray), Object(Closure))
#11 /var/www/html/selfoss/vendor/guzzlehttp/guzzle/src/Client.php(165): GuzzleHttp\\RequestFsm->__invoke(Object(GuzzleHttp\\Transaction))
#12 /var/www/html/selfoss/vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\\Client->send(Object(GuzzleHttp\\Message\\Request))
#13 /var/www/html/selfoss/helpers/WebClient.php(77): GuzzleHttp\\Client->get('https://kolabia...')
#14 /var/www/html/selfoss/helpers/Image.php(99): helpers\\WebClient::request('https://kolabia...')
#15 /var/www/html/selfoss/helpers/Image.php(75): helpers\\Image->loadImage('https://kolabia...', false, false)
#16 /var/www/html/selfoss/spouts/rss/feed.php(253): helpers\\Image->fetchFavicon('https://kolabia...', true)
#17 /var/www/html/selfoss/helpers/ContentLoader.php(177): spouts\
ss\\feed->getIcon()
#18 /var/www/html/selfoss/helpers/ContentLoader.php(35): helpers\\ContentLoader->fetch(Array)
#19 /var/www/html/selfoss/cliupdate.php(7): helpers\\ContentLoader->update()
#20 {main}
"}
```
The Favicon is saved as: https://mydomain.com/news/favicons/https://www.androidpolice.com/wp-content/themes/ap2/images/apple-touch-icon.png --> eg. mydomain + original url to favicon

**Comment by Offerel** [comment]
Strange, now after some time, the favicons are visible. It seems they are downloaded to the caching directory as png. I didn't have changed anything on the server and don't restartet any processes. I have no idea why the above errors are there.

**Comment by jtojnar** [comment]
I am unable to reproduce this with selfoss 2.18. 

![image](https://user-images.githubusercontent.com/705123/59878225-0c337b00-93a8-11e9-9f18-d7e104e25b5d.png)

https://s1.wp.com/i/favicon.ico, where I get redirected from https://kolabian.wordpress.com/favicon.ico has a wildcard certificate for `*.wp.com` so perhaps it is some kind of transient issue.

Do you see the issue for all feeds or just this specific one?

> The Favicon is saved as: mydomain.com/news/favicons/https://www.androidpolice.com/wp-content/themes/ap2/images/apple-touch-icon.png --> eg. mydomain + original url to favicon

That is weird. As fair as I know, selfoss hashes the URL for storage, so the resulting path should be something like mydomain.com/news/favicons/e4a18c08c674597238b585e2401a8dbe3af4af8f.png

**Comment by jtojnar** [comment]
> Strange, now after some time, the favicons are visible. It seems they are downloaded to the caching directory as png. I didn't have changed anything on the server and don't restartet any processes. I have no idea why the above errors are there.

Yeah, that sounds like temporary certificate hijinks.
