### ISSUE TITLE
2.17 breaks full-text-rss with call to Readability

### ISSUE THREAD

**Issue by Alrescha-git** [SSilence/selfoss#895]
After upgrading to 2.17, updates failed with message:

"selfoss.ERROR: fatal error: Class 'Readability' not found"

I do not use Readability for anything, but I did find a call to Readability() in the full-text RSS spout.  Switching those feeds to just RSS solved the update issue.

**Comment by rwky** [comment]
Hah you beat me to it by 3 minutes, also reported in #896

**Comment by jtojnar** [comment]
Thanks for reporting. Here is an [updated version](https://bintray.com/fossar/selfoss/selfoss-git/2.18-788d954#files).

**Comment by Binnette** [comment]
I think I'm also affected. Here is my error log:
```
[2017-11-27 21:13:38] selfoss.INFO: ftrss - Loading page: http://www.developpez.com/actu/175734/Le-passage-automatique-en-mode-de-navigation-privee-bientot-une-realite-dans-les-navigateurs-de-Microsoft-La-firme-depose-une-demande-de-brevet/
[2017-11-27 21:13:38] selfoss.INFO: ftrss - Extracting content
[2017-11-27 21:13:38] selfoss.DEBUG: ftrss - Cleaning content
[2017-11-27 21:13:38] selfoss.DEBUG: ftrss - Could not find Content-Type header in HTTP response
[2017-11-27 21:13:38] selfoss.DEBUG: ftrss - Character encoding: iso-8859-1
[2017-11-27 21:13:38] selfoss.ERROR: Class 'Readability' not found {"exception":"[object] (Error(code: 0): Class 'Readability' not found at /var/www/selfoss/libs/fulltextrss/content-extractor/ContentExtractor.php:203)\n[stacktrace]\n#0 /var/www/selfoss/spouts/rss/fulltextrss.php(221): ContentExtractor->process('<!DOCTYPE html>...', 'http://www.deve...')\n#1 /var/www/selfoss/spouts/rss/fulltextrss.php(99): spouts\\rss\\fulltextrss->extractContent('<!DOCTYPE html>...', 'http://www.deve...')\n#2 /var/www/selfoss/helpers/ContentLoader.php(151): spouts\\rss\\fulltextrss->getContent()\n#3 /var/www/selfoss/helpers/ContentLoader.php(39): helpers\\ContentLoader->fetch(Array)\n#4 /var/www/selfoss/controllers/Index.php(201): helpers\\ContentLoader->update()\n#5 /var/www/selfoss/vendor/bcosca/fatfree-core/base.php(1776): controllers\\Index->update(Object(Base), Array)\n#6 /var/www/selfoss/vendor/bcosca/fatfree-core/base.php(1599): Base->call(Array, Array, Array)\n#7 /var/www/selfoss/index.php(103): Base->run()\n#8 {main}"}
```

**Comment by Binnette** [comment]
Ok. So I update to version selfoss 2.18-788d954
And now, i got those errors in my log:

- j0k3r/graby#28
- `Exception(code: 0): fsockopen error:  at /var/www/selfoss/spouts/rss/feed.php:154)`

For the second one, I just restart my nginx and php and it is gone:
`service php7.0-fpm restart`
`service nginx restart`

I'm gona give a try to "master" latest version 94c681b

**Comment by Binnette** [comment]
I updated to 94c681b. After a brief composer and npm install, all errors are gone !
Now, i can grab my feeds ! Thanks a lot 😘

**Comment by Binnette** [comment]
Oops. I still have this little one in log. But it do not fail the "refreshing" of my feeds. 👍
But it do not download this feed in selfoss, so i can not read it through selfoss. 😢
```
[2017-11-27 22:00:16] selfoss.ERROR: error loading feed content for FEED_NAME {"exception":"[object] (Exception(code: 0): cURL error 60: SSL certificate problem: certificate has expired at /var/www/selfoss/spouts/rss/feed.php:160)
[stacktrace]
ss\\feed->load(Array)elpers/ContentLoader.php(98): spouts\
#1 /var/www/selfoss/helpers/ContentLoader.php(35): helpers\\ContentLoader->fetch(Array)
#2 /var/www/selfoss/controllers/Index.php(181): helpers\\ContentLoader->update()
#3 /var/www/selfoss/vendor/bcosca/fatfree-core/base.php(1776): controllers\\Index->update(Object(Base), Array)
#4 /var/www/selfoss/vendor/bcosca/fatfree-core/base.php(1599): Base->call(Array, Array, Array)
#5 /var/www/selfoss/index.php(80): Base->run()
#6 {main}
"}
```

So i get new "cert" at https://curl.haxx.se/ca/cacert.pem
And I reference it in my global php.ini
But it does not fix the error in selfoss.

it seems that this cainfo is used by "ringphp". But i do not know if ringphp is used to "refresh" my feeds.
`./vendor/guzzlehttp/ringphp/src/Client/ClientUtils.php:48:        if ($ca = ini_get('curl.cainfo')) {`

Do you want me to open a new bug in selfoss or in "ringphp" ? Or have you another solution ?

**Comment by jtojnar** [comment]
@Binnette This one is a different issue. Try opening the FEED_NAME feed in the browser, if the certificate has expired, updating the cacert probably will not help. If it does not look expired in your browser, could you check your server time?

**Comment by Binnette** [comment]
You are perfectly right ! I try the website in Firefox, and the website certificate has expired.
I sent a mail to the owner to ask him to update his cert.
I find a workaround by using some kind of proxy (in fact a site that aggregate a lot of feeds).

So i won't create a new issue 😉 thank you !
Only if you find it usefull, please consider improving the error log:
- From: cURL error 60: SSL certificate problem: certificate has expired
- To: cURL error 60: SSL certificate problem: certificate **of website www.example.com** has expired.

**Comment by jtojnar** [comment]
@Binnette I think the log message comes from curl itself, not much we can do about it, it should at least be possible to find out the feed name from the log. Thought I want to improve the error messages in the user interface a bit #986 so I suppose some of it could also be useful for the logs.

**Comment by martinsauter** [comment]
Experimenting with upgrading to 2.18 but despite this being marked as fixed I'm still getting an error + abort on refresh of the feeds because of call to undefined function Readability!?

[2018-04-17 20:08:16] selfoss.INFO: Extracting content for page: https://www.teltarif.de/nr0/simquadrat-lte-test/news/72321.html  
**[2018-04-17 20:08:17] selfoss.ERROR: Call to undefined function Readability\mb_regex_encoding()** {"exception":"[object] (Error(code: 0): Call to undefined function Readability\\mb_regex_encoding() at /var/www/selfoss-test2/vendor/j0k3r/php-readability/src/Readability.php:255)
[stacktrace]
#0 /var/www/selfoss-test2/vendor/j0k3r/php-readability/src/Readability.php(186): Readability\\Readability->loadHtml()
#1 /var/www/selfoss-test2/vendor/j0k3r/graby/src/Extractor/ContentExtractor.php(930): Readability\\Readability->__construct('\
\
\
\
\
\
<!doctype...', 'https://www.tel...', 'libxml', true)
#2 /var/www/selfoss-test2/vendor/j0k3r/graby/src/Extractor/ContentExtractor.php(203): Graby\\Extractor\\ContentExtractor->getReadability('\
\
\
\
\
\
<!doctype...', 'https://www.tel...', 'libxml', true)
#3 /var/www/selfoss-test2/vendor/j0k3r/graby/src/Graby.php(290): Graby\\Extractor\\ContentExtractor->process('\
\
\
\
\
\
<!doctype...', 'https://www.tel...')
#4 /var/www/selfoss-test2/vendor/j0k3r/graby/src/Graby.php(143): Graby\\Graby->doFetchContent('https://www.tel...')
#5 /var/www/selfoss-test2/spouts/rss/fulltextrss.php(61): Graby\\Graby->fetchContent('https://www.tel...')
ss\\fulltextrss->getContent()pers/ContentLoader.php(151): spouts\
#7 /var/www/selfoss-test2/helpers/ContentLoader.php(35): helpers\\ContentLoader->fetch(Array)
#8 /var/www/selfoss-test2/controllers/Index.php(181): helpers\\ContentLoader->update()
#9 /var/www/selfoss-test2/vendor/bcosca/fatfree-core/base.php(1806): controllers\\Index->update(Object(Base), Array, 'controllers\\\\Ind...')
#10 /var/www/selfoss-test2/vendor/bcosca/fatfree-core/base.php(1627): Base->call(Array, Array, Array)
#11 /var/www/selfoss-test2/index.php(80): Base->run()
#12 {ma

**Comment by martinsauter** [comment]
Great tip, "sudo apt install php-mbstring" fixed the issue! Thanks!!!
